#simply triggering download by update:w
trigger:
 - master

pool:
  vmImage:"ubuntu 16.04"

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world

