#simply triggering download by update:w

trigger:
 - master

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo updates at azure devops.
      
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install vsce'

